#!/bin/bash

USER=$1

source ./.env

pushd ..
# create key
docker run -v $PWD/vpn-data:/etc/openvpn --rm -it $SERVICE_NAME easyrsa build-client-full $USER nopass

# generate client file
docker run -v $PWD/vpn-data:/etc/openvpn --rm $SERVICE_NAME ovpn_getclient $USER > $CLIENT_FILES_PATH/$USER.ovpn
popd
