#!/bin/bash

source ./.env

docker stop $SERVICE_NAME || true && docker rm $SERVICE_NAME || true
docker image rm -f $SERVICE_NAME || true

pushd $DOCKER_VPN_PATH
docker build -t $SERVICE_NAME .

if [ ! -d ../vpn-data ]; then
  mkdir ../vpn-data
fi
popd

